import { today, addDays, addMonths } from "./domain.js";
export function createDemoData() {
  const now = today();
  return {
    user: {
      user_id: 101,
      full_name: "Nguyễn Minh Anh",
      email: "minhanh@example.com",
      phone: "0901234567",
    },
    facilities: [
      {
        facility_id: 1,
        name: "SafeSpace Thảo Điền",
        area: "TP. Hồ Chí Minh",
        address: "28 đường số 12, Thảo Điền, TP. Hồ Chí Minh",
        hours: "08:00 – 20:00",
        phone: "028 0000 0001",
        tag: "Được yêu thích",
        color: "blue",
      },
      {
        facility_id: 2,
        name: "SafeSpace Bình Thạnh",
        area: "TP. Hồ Chí Minh",
        address: "120 Nguyễn Xí, Bình Thạnh, TP. Hồ Chí Minh",
        hours: "08:00 – 20:00",
        phone: "028 0000 0002",
        tag: "Thuận tiện di chuyển",
        color: "teal",
      },
      {
        facility_id: 3,
        name: "SafeSpace Cầu Giấy",
        area: "Hà Nội",
        address: "36 Duy Tân, Cầu Giấy, Hà Nội",
        hours: "08:00 – 20:00",
        phone: "024 0000 0003",
        tag: "Không gian rộng",
        color: "indigo",
      },
    ],
    unitTypes: [
      {
        unit_type_id: 1,
        name: "Small",
        size: 5,
        dimensions: "2.5 × 2 × 2.5 m",
        climate: false,
        description: "Gọn gàng cho đồ cá nhân, sách và thùng carton.",
      },
      {
        unit_type_id: 2,
        name: "Medium",
        size: 12,
        dimensions: "4 × 3 × 2.5 m",
        climate: true,
        description: "Vừa vặn cho đồ nội thất của một căn hộ nhỏ.",
      },
      {
        unit_type_id: 3,
        name: "Large",
        size: 20,
        dimensions: "5 × 4 × 2.5 m",
        climate: true,
        description: "Rộng rãi cho hàng kinh doanh và nội thất lớn.",
      },
    ],
    rates: [1, 2, 3].flatMap((f) =>
      [1, 2, 3].map((t) => ({
        facility_id: f,
        unit_type_id: t,
        monthly_rate:
          [500000, 1200000, 2000000][t - 1] + (f === 3 ? 100000 : 0),
        available: f === 2 && t === 3 ? 0 : [8, 5, 3][t - 1],
      })),
    ),
    units: [
      {
        unit_id: 1,
        facility_id: 1,
        unit_type_id: 2,
        unit_number: "A-102",
        location: "Tầng 1 · Dãy A",
      },
      {
        unit_id: 2,
        facility_id: 2,
        unit_type_id: 1,
        unit_number: "B-015",
        location: "Tầng trệt · Dãy B",
      },
      {
        unit_id: 3,
        facility_id: 1,
        unit_type_id: 3,
        unit_number: "A-208",
        location: "Tầng 2 · Dãy A",
      },
    ],
    contracts: [
      {
        contract_id: "HD-2026-001",
        reservation_id: "DC-2026-001",
        customer_id: 101,
        unit_id: 1,
        start_date: addMonths(now, -2),
        end_date: addDays(now, 12),
        agreed_monthly_rate: 1200000,
        deposit_amount: 1200000,
        status: "EXPIRING",
      },
      {
        contract_id: "HD-2026-002",
        reservation_id: "DC-2026-002",
        customer_id: 101,
        unit_id: 2,
        start_date: addMonths(now, -1),
        end_date: addMonths(now, 2),
        agreed_monthly_rate: 500000,
        deposit_amount: 500000,
        status: "ACTIVE",
      },
      {
        contract_id: "HD-2026-003",
        reservation_id: "DC-2026-003",
        customer_id: 101,
        unit_id: 3,
        start_date: addDays(now, 2),
        end_date: addMonths(addDays(now, 2), 3),
        agreed_monthly_rate: 2000000,
        deposit_amount: 2000000,
        status: "DRAFT",
      },
    ],
    reservations: [
      {
        reservation_id: "DC-2026-003",
        customer_id: 101,
        facility_id: 1,
        unit_type_id: 3,
        start_date: addDays(now, 2),
        rental_period_months: 3,
        expected_end_date: addMonths(addDays(now, 2), 3),
        quoted_monthly_rate: 2000000,
        required_deposit: 2000000,
        estimated_amount: 8000000,
        status: "CONFIRMED",
        created_at: now,
      },
      {
        reservation_id: "DC-2026-004",
        customer_id: 101,
        facility_id: 3,
        unit_type_id: 1,
        start_date: addDays(now, 7),
        rental_period_months: 2,
        expected_end_date: addMonths(addDays(now, 7), 2),
        quoted_monthly_rate: 600000,
        required_deposit: 600000,
        estimated_amount: 1800000,
        status: "PENDING_PAYMENT",
        created_at: now,
      },
    ],
    payments: [
      {
        payment_id: "TT-2026-008",
        contract_id: "HD-2026-001",
        payment_type: "RENT",
        amount: 1200000,
        currency: "VND",
        due_date: addDays(now, 3),
        status: "PENDING",
      },
      {
        payment_id: "TT-2026-007",
        contract_id: "HD-2026-002",
        payment_type: "LOST_KEY_FEE",
        amount: 100000,
        currency: "VND",
        due_date: addDays(now, 5),
        status: "PENDING",
      },
      {
        payment_id: "TT-2026-006",
        contract_id: "HD-2026-003",
        payment_type: "RENT",
        amount: 6000000,
        currency: "VND",
        paid_at: addDays(now, -1),
        status: "PAID",
        payment_method: "BANK_TRANSFER",
      },
      {
        payment_id: "TT-2026-005",
        contract_id: "HD-2026-003",
        payment_type: "DEPOSIT",
        amount: 2000000,
        currency: "VND",
        paid_at: addDays(now, -1),
        status: "PAID",
        payment_method: "BANK_TRANSFER",
      },
    ],
    handovers: [
      {
        handover_id: "BG-003",
        contract_id: "HD-2026-003",
        scheduled_at: `${addDays(now, 2)}T09:00:00`,
        status: "SCHEDULED",
        staff_confirmed: false,
        customer_confirmed: false,
        initial_condition: "Chờ kiểm tra tại cơ sở.",
      },
      {
        handover_id: "BG-001",
        contract_id: "HD-2026-001",
        scheduled_at: `${addMonths(now, -2)}T10:00:00`,
        status: "HANDED_OVER",
        staff_confirmed: true,
        customer_confirmed: true,
        initial_condition:
          "Kho sạch, khô ráo. Khóa và thẻ ra vào hoạt động tốt.",
      },
    ],
    tickets: [
      {
        ticket_id: "HT-2026-012",
        customer_id: 101,
        contract_id: "HD-2026-002",
        unit_id: 2,
        issue_type: "LOCK",
        title: "Hỗ trợ cấp lại chìa khóa kho B-015",
        description:
          "Mình bị mất chìa khóa. Nhờ cơ sở hỗ trợ cấp lại và hướng dẫn thủ tục nhận chìa khóa mới.",
        status: "IN_PROGRESS",
        priority: "NORMAL",
        created_at: addDays(now, -1),
      },
      {
        ticket_id: "HT-2026-009",
        customer_id: 101,
        contract_id: "HD-2026-001",
        unit_id: 1,
        issue_type: "ACCESS_CARD",
        title: "Thẻ ra vào không nhận ở cổng",
        description: "Thẻ ra vào không hoạt động khi quẹt tại cổng chính.",
        status: "RESOLVED",
        priority: "NORMAL",
        created_at: addDays(now, -7),
      },
    ],
    renewals: [],
    returnRequests: [],
    paymentNotices: {},
  };
}
